import sqlite3

conn = sqlite3.connect('../bd/bancoapp.db')
cursor = conn.cursor()
cursor.execute("""SELECT * from estados""")
estados = cursor.fetchall()

caracter = ['(', ',', ')']
for estado in estados:
    file = open(f'{estado[1]}.kv', 'w+')
    file.write('MDFloatLayout:\n'
               '    FitImage:\n'
               '        id: bg_image\n'
               '        source: "{}.jpg"\n'
               '    MDToolbar:\n'
               '        id: toolbar\n'
               '        text: "df"\n'
               '        pos_hint: {"top": 1}\n'
               '        md_bg_color: [0,0,1,0]\n'
               '        anchor_title: "center"\n'
               '    MDCard:\n'
               '        orientation: "vertical"\n'
               '        size_hint: .94, None\n'
               '        height: box_top.height + box_bottom.height\n'
               '        focus_behavior: True\n'
               '        ripple_behavior: True\n'
               '        pos_hint: {"center_x": .5, "center_y": .19}\n'
               '        radius: 15, 15, 15, 15\n'
               '        elevation: 10\n'
               '\n'
               '        MDBoxLayout:\n'
               '            id: box_top\n'
               '            spacing: "20dp"\n'
               '            adaptive_height: True\n'
               '            padding: "10dp", "20dp", "10dp", "10dp"\n'
               '\n'
               '            MDBoxLayout:\n'
               '                id: text_box\n'
               '                orientation: "vertical"\n'
               '                adaptive_height: True\n'
               '                spacing: "10dp"\n'
               '                padding: "10dp", "10dp", 0, 0\n'
               '\n'
               '                MDLabel:\n'
               f'                    text: "{estado[2]}"\n'
               '                    font_name: "..assets/Fonts/Poppins-SemiBold"\n'
               '                    font_size: "25sp"\n'
               '                    theme_text_color: "Primary"\n'
               '                    bold: True\n'
               '                    size_hint_y: None\n'
               '                    height: "0"\n'
               '\n'
               '                MDLabel:\n'
               f'                    text: "{estado[1]}, Brasil"\n'
               '                    font_name: "..assets/Fonts/Montserrat-Regular"\n'
               '                    font_size: "10sp"\n'
               '                    text_color: (102, 103, 105)\n'
               '                    size_hint_y: None\n'
               '                    height: self.texture_size[1]\n'
               '                    pos_hint: {"center_x": .505}\n'
               '\n'
               '        MDBoxLayout:\n'
               '            id: box_bottom\n'
               '            orientation: "vertical"\n'
               '            adaptive_height: True\n'
               '            padding: "20dp", "5dp", "20dp", "20dp"\n'
               '\n'
               '            MDLabel:\n'
               '                text: "Sobre"\n'
               '                font_name: "..assets/Fonts/Montserrat-Regular"\n'
               '                font_size: "14sp"\n'
               '                theme_text_color: "Primary"\n'
               '                bold: True\n'
               '                size_hint_y: None\n'
               '                height: self.texture_size[1]\n'
               '                pos_hint: {"center_y": .5}\n'
               '                theme_text_color: "Primary"\n'
               '\n'
               '            MDLabel:\n'
               f'                text: "{estado[3]}"\n'
               '                font_name: "..assets/Fonts/Montserrat-Regular"\n'
               '                size_hint_y: None\n'
               '                height: self.texture_size[1]\n'
               '                pos_hint: {"center_y": .5}\n'
               '                theme_text_color: "Primary"\n'
               '                font_size: "10sp"')
#file.seek(0, 0)
#print(file.read())

# Possibilidade
